import type { Seller, Conversation, Request, OfferType } from './types'

export const DEPARTMENTS = [
  'CSE',
  'ECE',
  'EEE',
  'MECH',
  'CE',
  'IT',
  'AIDS',
  'AIML',
  'Pharmacy',
  'MBA',
  'MCA',
] as const

export const YEARS = [
  '1st Year',
  '2nd Year',
  '3rd Year',
  '4th Year',
  'PG 1st Year',
  'PG 2nd Year',
] as const

export const OFFER_TYPES: OfferType[] = ['Assignment', 'Lab Record', 'Project']

export const SUBJECTS = [
  'Data Structures',
  'Algorithms',
  'Database Management',
  'Web Development',
  'Machine Learning',
  'Operating Systems',
  'Computer Networks',
  'Software Engineering',
  'Digital Electronics',
  'Microprocessors',
  'Signal Processing',
  'Control Systems',
  'Thermodynamics',
  'Fluid Mechanics',
  'Engineering Drawing',
  'Mathematics',
  'Physics',
  'Chemistry',
  'English',
  'Management',
]

export const mockSellers: Seller[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    email: 'priya.sharma@college.edu',
    department: 'CSE',
    year: '3rd Year',
    role: 'be-writer',
    avatar: 'PS',
    avatarColor: '#6c63ff',
    verified: true,
    bio: 'CSE topper with 9.2 CGPA. Specialized in DSA, DBMS, and Web Dev. Quality assured work with proper formatting.',
    rating: 4.9,
    reviewCount: 47,
    ordersCompleted: 52,
    responseTime: '< 1 hour',
    deliveryDays: 2,
    pricePerPage: 50,
    offers: ['Assignment', 'Lab Record', 'Project'],
    subjects: ['Data Structures', 'Algorithms', 'Database Management', 'Web Development'],
  },
  {
    id: '2',
    name: 'Rahul Verma',
    email: 'rahul.verma@college.edu',
    department: 'ECE',
    year: '4th Year',
    role: 'be-writer',
    avatar: 'RV',
    avatarColor: '#43e097',
    verified: true,
    bio: 'ECE final year with internship at Texas Instruments. Expert in analog circuits, embedded systems.',
    rating: 4.7,
    reviewCount: 31,
    ordersCompleted: 38,
    responseTime: '< 2 hours',
    deliveryDays: 3,
    pricePerPage: 45,
    offers: ['Assignment', 'Lab Record'],
    subjects: ['Digital Electronics', 'Microprocessors', 'Signal Processing'],
  },
  {
    id: '3',
    name: 'Sneha Patel',
    email: 'sneha.patel@college.edu',
    department: 'MECH',
    year: '3rd Year',
    role: 'be-writer',
    avatar: 'SP',
    avatarColor: '#f7c948',
    verified: true,
    bio: 'Mechanical engineering student with strong CAD skills. AutoCAD, SolidWorks certified.',
    rating: 4.8,
    reviewCount: 28,
    ordersCompleted: 35,
    responseTime: '< 3 hours',
    deliveryDays: 4,
    flatPrice: 500,
    offers: ['Assignment', 'Project'],
    subjects: ['Thermodynamics', 'Fluid Mechanics', 'Engineering Drawing'],
  },
  {
    id: '4',
    name: 'Amit Kumar',
    email: 'amit.kumar@college.edu',
    department: 'IT',
    year: '2nd Year',
    role: 'be-writer',
    avatar: 'AK',
    avatarColor: '#ff6b6b',
    verified: false,
    bio: 'Full stack developer with React and Node.js experience. Quick turnaround time guaranteed.',
    rating: 4.5,
    reviewCount: 15,
    ordersCompleted: 18,
    responseTime: '< 1 hour',
    deliveryDays: 2,
    pricePerPage: 40,
    offers: ['Assignment', 'Project'],
    subjects: ['Web Development', 'Database Management', 'Software Engineering'],
  },
  {
    id: '5',
    name: 'Kavya Reddy',
    email: 'kavya.reddy@college.edu',
    department: 'AIML',
    year: 'PG 1st Year',
    role: 'be-writer',
    avatar: 'KR',
    avatarColor: '#6c63ff',
    verified: true,
    bio: 'PG student specializing in Machine Learning and Deep Learning. Research papers published.',
    rating: 4.9,
    reviewCount: 22,
    ordersCompleted: 25,
    responseTime: '< 4 hours',
    deliveryDays: 5,
    pricePerPage: 75,
    offers: ['Assignment', 'Lab Record', 'Project'],
    subjects: ['Machine Learning', 'Algorithms', 'Mathematics'],
  },
  {
    id: '6',
    name: 'Arjun Singh',
    email: 'arjun.singh@college.edu',
    department: 'MBA',
    year: 'PG 2nd Year',
    role: 'be-writer',
    avatar: 'AS',
    avatarColor: '#43e097',
    verified: true,
    bio: 'MBA Finance specialization. Case studies, business plans, financial analysis expert.',
    rating: 4.6,
    reviewCount: 19,
    ordersCompleted: 24,
    responseTime: '< 2 hours',
    deliveryDays: 3,
    flatPrice: 800,
    offers: ['Assignment', 'Project'],
    subjects: ['Management', 'Mathematics', 'English'],
  },
]

export const mockConversations: Conversation[] = [
  {
    id: '1',
    participantId: '1',
    participant: mockSellers[0],
    subject: 'DBMS Assignment',
    offerType: 'Assignment',
    messages: [
      {
        id: 'm1',
        senderId: 'me',
        text: 'Hi, I need help with my DBMS assignment on normalization',
        timestamp: new Date(Date.now() - 3600000 * 2),
        read: true,
      },
      {
        id: 'm2',
        senderId: '1',
        text: 'Sure! I can help. How many pages and what topics?',
        timestamp: new Date(Date.now() - 3600000 * 1.5),
        read: true,
      },
      {
        id: 'm3',
        senderId: 'me',
        text: 'Around 10 pages covering 1NF to BCNF with examples',
        timestamp: new Date(Date.now() - 3600000),
        read: true,
      },
      {
        id: 'm4',
        senderId: '1',
        text: 'Perfect! I can deliver in 2 days. Ready to proceed?',
        timestamp: new Date(Date.now() - 1800000),
        read: false,
      },
    ],
    lastMessage: 'Perfect! I can deliver in 2 days. Ready to proceed?',
    lastMessageTime: new Date(Date.now() - 1800000),
    unreadCount: 1,
    isOnline: true,
  },
  {
    id: '2',
    participantId: '3',
    participant: mockSellers[2],
    subject: 'CAD Project',
    offerType: 'Project',
    messages: [
      {
        id: 'm1',
        senderId: 'me',
        text: 'Need a 3D model for my mechanical project',
        timestamp: new Date(Date.now() - 86400000),
        read: true,
      },
      {
        id: 'm2',
        senderId: '3',
        text: 'What kind of model? Mechanical part or assembly?',
        timestamp: new Date(Date.now() - 82800000),
        read: true,
      },
    ],
    lastMessage: 'What kind of model? Mechanical part or assembly?',
    lastMessageTime: new Date(Date.now() - 82800000),
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: '3',
    participantId: '5',
    participant: mockSellers[4],
    subject: 'ML Lab Record',
    offerType: 'Lab Record',
    messages: [
      {
        id: 'm1',
        senderId: '5',
        text: 'Your lab record is ready for review!',
        timestamp: new Date(Date.now() - 172800000),
        read: true,
      },
    ],
    lastMessage: 'Your lab record is ready for review!',
    lastMessageTime: new Date(Date.now() - 172800000),
    unreadCount: 0,
    isOnline: true,
  },
  {
    id: '4',
    participantId: '2',
    participant: mockSellers[1],
    subject: 'Embedded Systems',
    offerType: 'Assignment',
    messages: [
      {
        id: 'm1',
        senderId: 'me',
        text: 'Can you help with 8051 microcontroller assignment?',
        timestamp: new Date(Date.now() - 259200000),
        read: true,
      },
      {
        id: 'm2',
        senderId: '2',
        text: 'Yes, I specialize in this. Send me the details.',
        timestamp: new Date(Date.now() - 255600000),
        read: false,
      },
    ],
    lastMessage: 'Yes, I specialize in this. Send me the details.',
    lastMessageTime: new Date(Date.now() - 255600000),
    unreadCount: 1,
    isOnline: false,
  },
  {
    id: '5',
    participantId: '6',
    participant: mockSellers[5],
    subject: 'Business Case Study',
    offerType: 'Assignment',
    messages: [
      {
        id: 'm1',
        senderId: '6',
        text: 'Order completed! Please confirm delivery.',
        timestamp: new Date(Date.now() - 432000000),
        read: true,
      },
    ],
    lastMessage: 'Order completed! Please confirm delivery.',
    lastMessageTime: new Date(Date.now() - 432000000),
    unreadCount: 0,
    isOnline: true,
  },
]

export const mockRequests: Request[] = [
  {
    id: 'r1',
    type: 'Assignment',
    subject: 'Data Structures',
    description: 'Need help with tree traversal and graph algorithms assignment',
    budget: 500,
    deadline: '3 days',
    status: 'active',
    createdAt: new Date(Date.now() - 86400000),
    responses: 5,
  },
  {
    id: 'r2',
    type: 'Lab Record',
    subject: 'Database Management',
    description: 'Complete lab record with SQL queries and ER diagrams',
    budget: 400,
    deadline: '5 days',
    status: 'in-progress',
    createdAt: new Date(Date.now() - 172800000),
    responses: 3,
  },
  {
    id: 'r3',
    type: 'Project',
    subject: 'Web Development',
    description: 'E-commerce website using React and Node.js',
    budget: 2000,
    deadline: '2 weeks',
    status: 'completed',
    createdAt: new Date(Date.now() - 604800000),
    responses: 8,
  },
]
